### ISSUE TITLE
Good day, everyone!

### ISSUE THREAD

**Issue by ChrisHaravata** [beercsv/world#1]
My group has been looking everywhere for a beer dataset with the '**çolor**' and '**álcolhol** content' features. We have looked everywhere, but either there is no color, or there is no alcohol content. Can anyone please help in pointing us to the right direction?

Thanks a bunch!!

**Comment by geraldb** [comment]
Please send questions to the [forum / mailing list](https://groups.google.com/group/beerdb). Cheers. Prost. Kampai.
